### ISSUE TITLE
Improve Send Now UX

### ISSUE THREAD

**Issue by hongee** [daily-bruin/meow#148]
- Change the color of the send now button to something stronger like orange or red to make it visually obvious that this is separate and _dangerous_ action
- Even with a color change, there needs to be a confirmation dialog to prevent accidents
- As post sending is done asynchronously, the backend may not be able to provide immediate feedback of success or failure. A simple solution should just to be redirect users back to the homepage and allow the main panel to show the status of the meow

---

The above should all be minor 1 liner changes. Does anyone have the bandwidth to take them on this weekend?

**Comment by dustinnewman98** [comment]
@hongee Issues addresses in #149 I believe, right? Can we close the issue?
