### ISSUE TITLE
"Post Now button" with Confirmation Dialog

### ISSUE THREAD

**Issue by hongee** [daily-bruin/meow#63]
Posts which are Readied should have a button that allows them to post immediately, with a confirmation dialog showing the message and everything to be sent out. The permission also needs to be set to Copy only.

### Tasks
- [ ] Post now button
- [ ] Confirmation Dialog
- [ ] Give permissions to Copy

**Comment by dustinnewman98** [comment]
See https://github.com/daily-bruin/meow/pull/120

**Comment by alexanderqchen** [comment]
Can you reopen this? There is no confirmation dialog yet.

Also, using send now doesn't redirect to the dashboard yet, so I was working on that too.

**Comment by siowleo** [comment]
My bad I forgot about the ui goodies
