### ISSUE TITLE
Clarify Meow setting object labels

### ISSUE THREAD

**Issue by siowleo** [daily-bruin/meow#82]
Currently Meow setting objects don't specify what they contain, which causes us to inefficiently go into each object to see what they contain. We should label each object with the appropriate label.

**Comment by alexanderqchen** [comment]
![image](https://user-images.githubusercontent.com/12878275/33517843-1078fe68-d740-11e7-8dc3-ff3e2223b364.png)

I found that this was a problem with python2 --> python3 conversion. In the models.py file, the function __unicode__ named the model objects in python2, but in python3, it should be __str__. I changed the name of this function for the MeowSetting object, but also every other __unicode__ function in the file.
